// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MlSentimentFirstML.Model
{
    public class ModelInput
    {
        [ColumnName("PhraseId"), LoadColumn(0)]
        public float PhraseId { get; set; }


        [ColumnName("SentenceId"), LoadColumn(1)]
        public float SentenceId { get; set; }


        [ColumnName("Phrase"), LoadColumn(2)]
        public string Phrase { get; set; }


        [ColumnName("Sentiment"), LoadColumn(3)]
        public string Sentiment { get; set; }


    }
}
